### ISSUE TITLE
Update twig dependency

### ISSUE THREAD

**Issue by athos7933** [KnpLabs/DictionaryBundle#111]
Need to updates twig dependency to be compatible with new 3.0.

**Comment by PedroTroller** [comment]
It will be released with v3.1 :wink:

**Comment by lukepass** [comment]
Hello, any news on this? I am using Symfony 4.4 and I cannot install this bundle because it requires twig 3. Thanks!

**Comment by PedroTroller** [comment]
V3.1 released

**Comment by athos7933** [comment]
Thanks a lot !
