### ISSUE TITLE
Symfony 5 support

### ISSUE THREAD

**Issue by OwlyCode** [KnpLabs/DictionaryBundle#120]
Hello,

Do you plan to add Symfony 5 support? I forked this bundle and made it ready for Symfony 5 but there is a BC break that will make Symfony 3.4 no longer supported on PHP less than 7.4 : the DataCollectorInterface::collect signature changed and contravariant parameter support has only been added in PHP 7.4.

I can provide you the PR but what can we do about Symfony 3.4?

**Comment by PedroTroller** [comment]
@OwlyCode verson 3.1 is nearly finished and compatible with SF5 and PHP7.4. You can use the tag `3.1@dev` if you are in a rush :wink: 
I will try to release it today.

**Comment by PedroTroller** [comment]
Released https://packagist.org/packages/knplabs/dictionary-bundle#v3.1.0
