### ISSUE TITLE
Validator fail with empty value

### ISSUE THREAD

**Issue by NiR-** [KnpLabs/DictionaryBundle#18]
Currently if you try to validate an empty value with the DictionaryBundle it will add a violation. I think this behavior should be avoided, and let the developer take care of this.

Two ways:
  * Ignore empty value (BC break)
  * Add an option into the constraint to not validate empty value (no BC break)

What do you think guys ?

**Comment by docteurklein** [comment]
2nd option seems the best fit.

**Comment by Shivoham** [comment]
2nd option :+1:

**Comment by cursedcoder** [comment]
2

**Comment by aguidis** [comment]
2nd option :+1:
