### ISSUE TITLE
Support for Symfony 6.4

### ISSUE THREAD

**Issue by virtualize** [KnpLabs/DictionaryBundle#244]
Hello. Are there plans to support the latest Symfony LTS 6.4? If yes within what timeframe?
I've seen this pull request [#207](https://github.com/KnpLabs/DictionaryBundle/pull/207) but it has been touched for months.

What can I do to help?

**Comment by PedroTroller** [comment]
I need time. The end of 2023 and the beginning of 2024 have not been easy, but I've found the time to finish everything. Sorry about that.
