### ISSUE TITLE
[RFC] "php": ">=5.4" ?

### ISSUE THREAD

**Issue by PedroTroller** [KnpLabs/DictionaryBundle#40]
``` php
try {
    $this->keepCompatibility('5.3');
} catch (BoringException $ex) {
    $this->keepCompatibility('5.4');

    throw new TableFlipException();
}
```

**Comment by PedroTroller** [comment]
@Einenlum @NiR- @Shivoham

**Comment by NiR-** [comment]
@PedroTroller As discussed, I would prefer to not support unmaintained PHP version. As of now, [only php 5.6 & 7.0 are maintained](http://php.net/supported-versions.php). So I would drop PHP 5.3, 5.4 & 5.5.

**Comment by Nek-** [comment]
v2 is canceled? On the topic, IMHO the best choice is to follow Symfony requirements.

**Comment by NiR-** [comment]
@Nek- Nope it's not cancelled but we didn't had time to push it forward so far. Have you any link whose provide detailed informations about extended supports by OS teams?

**Comment by Nek-** [comment]
Here it is for debian:

> [2017-03-27] Accepted 5.4.45-0+deb7u8 in wheezy-security (high) (Markus Koschany)
> https://packages.qa.debian.org/p/php5.html

(which is a new version approximately 2 years after official EOL)

**Comment by NiR-** [comment]
To give more insights:

* [Next debian release (Debian 9, codename "stretch") will be out on 2017-06-17, and will be shipped only with php7](https://lists.debian.org/debian-devel-announce/2016/01/msg00002.html) ;
* [Current debian release, shipped with php5.6 and php7, will be out of support in June 2020](https://wiki.debian.org/DebianReleases).

Thus I think we should drop support for PHP < 5.6.
