### ISSUE TITLE
symfony 4.0.8 + dependency injection

### ISSUE THREAD

**Issue by u1tr0n** [KnpLabs/DictionaryBundle#73]
bundle version: v2.0.1
Symfony 4.0.8
when i try to use it in controller like:
`$this->get('knp_dictionary.registry')->get('my_dictionary');`
it make an error:

> The "knp_dictionary.registry" service or alias has been removed or inlined when the container was compiled. You should either make it public, or stop using the container directly and use dependency injection instead.

**Comment by PedroTroller** [comment]
@u1tr0n thanks a lot, it's fixed with in the v2.0.2.
